#!/usr/bin/env zsh
#
# Defines some useful aliases, post-zshrc.
#
# Editor:
#   Jeffrey Serio <hyperreal64@gmail.com>
#

# Use batman as man-page program if exists
if [ "$(command -v batman)" ]; then
    alias man="batman"
fi

# SSH keys
alias privkey="more ~/.ssh/id_ed25519 | xclip -selection clipboard | echo '=> Private key copied to clipboard'"
alias pubkey="more ~/.ssh/id_ed25519.pub | xclip -selection clipboard | echo '=> Public key copied to clipboard'"

# Networking
alias pubip="curl ipinfo.io"
alias netCons="lsof -i"
alias tulp="ss -tulp"
alias openPorts="sudo lsof -i | grep LISTEN"
alias pong="ping -c 3 www.google.com"

# File management
alias grep="grep --color"
alias sgrep="grep -R -n -H -C 5 --exclude-dir={.git} "
alias t="tail -f"
alias -g C="| wc -l"
alias -g H="| head"
alias -g F="| fzf"
alias -g T="| tail"
alias -g G="| grep"
alias -g L="| less"
alias -g M="| most"
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"
alias rm="rm -i"
alias cp="cp -i"
alias mv="mv -i"
alias lslog="ls /var/log/"
if [ $(command -v lsd) ]; then
    alias ls="lsd"
fi
alias la="ls -a"
alias ll="ls -l"
alias lal="ls -al"

# Trim newlines and copy to clipboard
alias -g CC="| tr -d '\\n' | xclip -selection clipboard"

# System/Power management
alias reboot="sudo systemctl reboot"
alias shut="sudo systemctl poweroff"

