#!/usr/bin/env zsh
#
# Defines some useful functions, post-zshrc
#
# Editor:
#   Jeffrey Serio <hyperreal64@gmail.com>
#

# Show shell files
zalias() { bat "${HOME}/.zsh/zaliases"; }
zenv() { bat "${HOME}/.zshenv"; }
zfuncs() { bat "${HOME}/.zsh/zfunctions"; }

# Do an ls after cd
cd() { builtin cd "$@" && ls; }

# Create a new directory and enter it
mkd() { mkdir -p "$@" && cd "$_"; }

# Refresh shell env
restart() { exec $SHELL $SHELL_ARGS "$@"; }
rsrc() { cd && clear && restart; }

# pids
pids() { pgrep -a "$@"; }

# Fuzzies for fzf
fd() {
  if [ $(command -v fd) ]; then
    FZF_DEFAULT_COMMAND='fd . -t f' \
      fzf --bind 'ctrl-d:reload(fd . -t d),ctrl-f:reload($FZF_DEFAULT_COMMAND)' \
      --height=50% --layout=reverse
  else
    FZF_DEFAULT_COMMAND='find . -type f' \
      fzf --bind 'ctrl-d:reload(find . -type d),ctrl-f:reload($FZF_DEFAULT_COMMAND)' \
      --height=50% --layout=reverse
  fi
}

igr() {
  declare preview='bat --color=always --style=header,numbers -H {2} {1} | grep -C3 {q}'

  while getopts ':1' x; do
    case "$x" in
      l) list_files=1
        preview='bat --color=always --style=header,numbers {1} | grep -C3 {q}'
        ;;
    esac
  done
  shift $(( OPTIND - 1 ))
  unset x OPTARG OPTIND
 
  rg --color=always -n ${list_files:+-l} "$1" 2> /dev/null |
    fzf -d: \
    --ansi \
    --query="$1" \
    --phony \
    --bind="change:reload:rg -n ${list_files:+-l} --color=always {q}" \
    --bind='enter:execute:v {1}' \
    --preview="[[ -n {1} ]] && $preview"
}


