#!/usr/bin/env zsh
#
# Defines local variables, post-zshrc.
#
# Editor:
#   Jeffrey Sero <hyperreal64@gmail.com>
#

export BAT_THEME="Dracula"
export RESTIC_PASSWORD_FILE="${HOME}/.restic-pw"
export YSU_MESSAGE_POSITION="after"
export YSU_HARDCORE=1

# Load ~/.dir_colors if exists
[[ -f "${HOME}/.dir_colors" ]] && eval $(dircolors -b "${HOME}/.dir_colors")

# Set path
typeset -U PATH path
path=(
    /usr/local/bin
    /usr/local/sbin
    "${HOME}/bin"
    "${HOME}/.local/bin"
    "${GOPATH}/bin"
    "${GOROOT}/bin"
    "${PIPX_BIN_DIR}"
    "${path[@]}"
)
export PATH


